### ISSUE TITLE
Extend replacement for PlanQK Service Tasks

### ISSUE THREAD

**Issue by wederbn** [PlanQK/workflow-modeler#65]
**Problem Statement:**

When replacing a PlanQK Service Task, the following subprocess is inserted:

![image](https://github.com/PlanQK/workflow-modeler/assets/20323063/5fe0a0a1-12c8-4b22-be82-880b0c444fa0)

To ease the understanding of the subprocess, the sequence flow shouldn´t be merged at the Timer Event.
Instead, it should be merged using a separate XOR gateway before the event.

Furthermore, the PlanQK Service Task should be configurable with a maximum number of iterations (also enabling unlimited iterations) for the polling.
This should be reflected by the loop, leading to an Error End Event in case the maximum number of iterations is met before the service returns a result.

Finally, the Error End Event on the right should be connected to the last Service Task using a Boundary Event instead of regular sequence flow.

**Tasks:**

- [ ] Add additional merging XOR Gateway
- [ ] Add configuration for max iterations
- [ ] Add transformation reflecting max iterations
- [ ] Add Error Boundary Event to last Service Task
