### ISSUE TITLE
Extend Test Setup

### ISSUE THREAD

**Issue by wederbn** [PlanQK/workflow-modeler#85]
**Problem Statement:**
Currently, only the workflow modeler itself, as well as the upload of workflow models to the Camunda engine are supported as test cases.
However, the integration tests with all other components (script splitter, hybrid program generator, Winery/OpenTOSCA, ...) are missing.

**Expected Behavior:**
The different components should be added as [services](https://github.com/PlanQK/workflow-modeler/blob/master/.github/workflows/run-npm-test.yml#L14) within the GitHub workflows, and corresponding tests should validate the functionality of the integration.

**Tasks:**

- [ ] Add [OT](https://github.com/OpenTOSCA) tests (e.g., retrieval of deployment models, upload to the container, ...)
- [ ] Add [Script Splitter](https://github.com/UST-QuAntiL/qscript-splitter) test (check if workflow is generated correctly)
- [ ] Add [Hybrid Runtime Handler](https://github.com/UST-QuAntiL/qiskit-runtime-handler) (check if rewritten workflow has the expected structure)
