### ISSUE TITLE
User-supported Hardware Selection

### ISSUE THREAD

**Issue by wederbn** [PlanQK/workflow-modeler#93]
**Problem Statement:**
Currently, the hardware selection is only supported in an automated manner, invoking the NISQ Analyzer and automatically selecting one of the suitable devices based on selection strategies defined during workflow modeling.

**Expected Behavior:**
The hardware selection should also be possible in a user-orchestrated manner, i.e., by navigating to the NISQ Analyzer UI and performing all required steps for the selection

**Tasks:**

- [x] Add a new config attribute to the hardware selection subprocess: Automated Selection (Checkbox, default: true)
- [x] During workflow transformation perform the currently implemented transformation if Automated Selection == true
- [x] If Automated Selection == False (or undefined/!=true for backward compatibility): Add a user task instead of the tasks invoking the NISQ Analyzer and post-processing the results
- [x] Create a form displayed in the Camunda Engine UI redirecting the user to the NISQ Analyzer UI (in the context of the circuit generated within the workflow, @salmma can provide further information on which endpoint to use)
- [x] The form should also provide a result field to insert the selection done by the user, which has to be injected into the correct variable to enable further processing within the workflow

**Comment by salmma** [comment]
independent issue

**Comment by salmma** [comment]
Further Notes:

NISQ Analyzer UI - nice to have:
- hide Execute Buttons
- route directly to QPU-Selection Tab

NISQ Analyzer Backend:
- store QASM String as implementation in backend, then route from Camunda Engine UI to the implementation
