### ISSUE TITLE
Pattern-based Generation and Adaptation of Quantum Workflows

### ISSUE THREAD

**Issue by wederbn** [PlanQK/workflow-modeler#94]
**Problem Statement:**
Currently, the user has to model quantum workflows manually, which is very complex and error-prone, especially when including advanced techniques, such as warm-starting or circuit cutting.

**Expected Behavior:**
An approach is required to automatically generate quantum workflows based on a set of selected [patterns](https://quantumcomputingpatterns.org/#/).
Furthermore, it should also be supported to adapt quantum workflows automatically when attaching patterns to activities.

**Tasks:**

- [x] #95
- [x] Restrict the pattern selection based on defined rules (e.g., currently, exactly one algorithmic pattern must be selected)
- [x] Retrieve the concrete solution defined for the selected algorithmic pattern:
     - [x] https://github.com/UST-QuAntiL/qc-atlas/issues/217
     - [x] If the solution is a workflow: Open the workflow in the modeler
     - [x] If the solution is a Python file: Invoke script splitter, retrieve resulting workflow, open in modeler
- [x] Enable attachment of patterns to the resulting workflow:
    - [x] Enable visualization of patterns attached to activities and subprocesses
    - [x] Automatically attach behavioral and augmentation patterns to the workflow generated/loaded in the previous step
    - [x] Enable manual adaptation of attached patterns (remove, add new, etc.)
- [x] Transformation of attached patterns:
    - [x] Add knowledge base for the transformation
    - [x] Transformation must be done before other transformations, e.g., QuantME transformation
    - [x] Add example rules:
        - [x] REM pattern: Add REM task after circuit execution tasks within the subprocess to which the pattern is attached. Also after result combination task in case cutting is applied.
        - [x] Warm-Starting pattern: Add WS task before VQA starts. Before Circuit Loading. 
        - [x] Cutting pattern: Add cutting and combination tasks before/after execution
            - [x] https://github.com/PatternAtlas/pattern-atlas-content/issues/28
        - [x] Error correction: After circuit loading and before circuit execution 
    - [x] Store transformations to enable visualizing a pattern view
- [x] Add tests for attachment/splitting/transformation/etc.
- [x] Add documentation on how to use the feature

@mbeisel, @vietzd: Please refine where required

**Comment by salmma** [comment]
**!!!most important issue!!!**
from step 3 on depending on concrete solution connection provided by @GeorgDaniel (and the thesis)

**Comment by wederbn** [comment]
Closed by #161
