### ISSUE TITLE
Add a popup displaying the available patterns and support the user selection of a suitable subset

### ISSUE THREAD

**Issue by wederbn** [PlanQK/workflow-modeler#95]
Add a popup displaying the available patterns and support the user selection of a suitable subset.

**Tasks:**

- [x] Add a new pattern plugin (or should it be included in QuantME? I think it is independent functionality)
- [x] Add config attribute to specify Pattern Atlas endpoint
- [x] Add a new button to open the pattern selection popup
- [x] Allow to add/ remove algorithmic patterns
- [x] Retrieve available patterns from Pattern Atlas when the popup is opened (add field to pattern identifying the category of patterns: algorithmic, behavioral, augmentation)
- [x] The pattern selection popup should be a dialog with the parts:
    - [x] Algorithmic: Select an algorithm for which a quantum workflow should be generated/loaded/adapted
    - [x] Behavioral: Select how the algorithm should be executed (as a workflow, using a hybrid runtime, etc.)
    - [x] Augmentation: Select which further features should be added to improve the execution (cutting, WS, REM, etc.)

**Comment by wederbn** [comment]
Closed by #108
